markdown: kramdown
title: Kurotaku's Userscripts
description: A collection with Quality-of-life userscripts for Steam, Twitch, and more. made by Kurotaku
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
- google3cd44068f1e29935.html